services:
  db:
    image: postgres:15-alpine
    container_name: mmd_postgres_db
    restart: always
    environment:
      # Variables are pulled from the .env file
      POSTGRES_USER: ${POSTGRES_USER:-train}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Ankara06}
      POSTGRES_DB: ${POSTGRES_DB:-traindb}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-train} -d ${POSTGRES_DB:-traindb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mmd_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mmd_fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    # Pass all .env variables to the container
    env_file:
      - .env
    environment:
      # We override the local URL with the Docker network URL
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./saved_models:/app/saved_models
      - ./data:/app/data

volumes:
  mmd_postgres_data: